# Generated by Django 4.1.1 on 2023-04-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_short',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
